# Logging configuration
log_level: INFO
log_folder: "./resources/logs"

# Input and Output folders
input_folder: "./resources/psarcs"
output_folder: "./resources/output"

# Audio extraction
extract_audio: true

# File overwriting behavior
overwrite_output: false